# -*- coding: utf-8 -*-
"""autism_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i9FIDhkBsu1cvpbmRZECH_256B25AeIF
"""

import streamlit as st
import pandas as pd
import numpy as np
from ucimlrepo import fetch_ucirepo
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

# -----------------------------
# Load and prepare the dataset
# -----------------------------
@st.cache_data
def load_data():
    data = fetch_ucirepo(id=426)  # UCI Adult Autism dataset
    df = pd.concat([data.data.features, data.data.targets], axis=1)

    # Drop columns we don't want to use
    df = df.drop(
        columns=[
            "country_of_res",
            "relation",
            "age_desc",
            "result",
            "age",
            "gender",
            "ethnicity",
            "used_app_before",
        ]
    )

    # Clean missing values
    df = df.replace("?", np.nan).dropna()

    # Encode features
    df["jaundice"] = df["jaundice"].map({"yes": 1, "no": 0})

    le_family = LabelEncoder()
    df["family_pdd"] = le_family.fit_transform(df["family_pdd"])

    # Target encoding
    df["class"] = df["class"].map({"NO": 0, "YES": 1})

    return df, le_family


@st.cache_resource
def train_model(df):
    X = df.drop(columns="class")
    y = df["class"]
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X, y)
    return model, X.columns.tolist()


def main():
    st.title("🧠 Autism Prediction App")
    st.write(
        "Please answer the following questions. "
        "This tool estimates the likelihood of autism-related traits based on your responses. "
        "It is **not** a medical diagnosis."
    )

    # Load data and model
    df, le_family = load_data()
    model, feature_cols = train_model(df)

    # Questions (these correspond to the AQ-10 style items)
    questions = [
        "I am highly sensitive to small sounds that others often miss.",
        "I tend to focus more on small details than the overall picture.",
        "I find it difficult to multitask or do more than one thing at a time.",
        "It’s hard for me to resume what I was doing after being interrupted.",
        "I struggle to understand implied meanings in conversations.",
        "I often can’t tell if someone is getting bored while I'm talking.",
        "I have difficulty figuring out characters’ intentions when reading stories.",
        "I enjoy collecting detailed information about specific categories of things (e.g., cars, birds).",
        "I find it hard to understand what someone is feeling just by looking at their face.",
        "I often find it difficult to understand what others intend to do.",
    ]

    with st.form("autism_form"):
        answers = [
            1 if st.radio(q, ["Yes", "No"], key=q) == "Yes" else 0 for q in questions
        ]
        jaundice = st.radio("Experienced jaundice as a child?", ["yes", "no"])
        family_pdd = st.selectbox("Family history of PDD (pervasive developmental disorder)?", le_family.classes_)
        submitted = st.form_submit_button("Predict")

    if submitted:
        # Build input row in the same order as training features
        input_features = answers + [
            1 if jaundice == "yes" else 0,
            le_family.transform([family_pdd])[0],
        ]

        input_df = pd.DataFrame([input_features], columns=feature_cols)

        prediction = model.predict(input_df)[0]
        proba = model.predict_proba(input_df)[0][1]

        # --- Display Results ---
        st.subheader("🧾 Prediction Result")
        st.metric(
            label="Predicted ASD Likelihood Score",
            value=f"{proba * 100:.1f}%",
        )

        if prediction == 1:
            st.warning(
                "⚠️ **Likely Positive for autism traits.**\n\n"
                "Your pattern of responses is similar to individuals who screened positive "
                "for autism-related traits in the dataset. "
                "This is **not a diagnosis**—please consult a qualified professional for further evaluation."
            )
        else:
            st.success(
                "✅ **Likely Negative for autism traits.**\n\n"
                "Based on this screening tool, your responses do not show strong indicators "
                "of autism-related traits. This does **not** rule out autism; it is only a screening result."
            )

        # --- Score Position Bar Chart ---
        st.subheader("📊 How Your Score Compares")
        fig, ax = plt.subplots(figsize=(6, 0.8))
        ax.barh(["Your Score"], [proba], color="orange", height=0.3)
        ax.set_xlim(0, 1)
        ax.set_xlabel("Autism Likelihood")
        ax.set_yticks([0])
        ax.set_yticklabels(["Your Score"], fontsize=10)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_visible(False)
        plt.tight_layout()
        st.pyplot(fig)


if __name__ == "__main__":
    main()